/**
 * This file is auto-generated by @hey-api/openapi-ts
 * Run `pnpm openapi-ts` to regenerate
 */

import type { QueryKey, UseQueryOptions } from '@tanstack/react-query';

import { usersMeRetrieve } from '../sdk.gen';
import type { User } from '../types.gen';

export const usersMeRetrieveQueryKey = (): QueryKey => ['users', 'me'];

export const usersMeRetrieveOptions = (): UseQueryOptions<User, Error> => ({
  queryKey: usersMeRetrieveQueryKey(),
  queryFn: () => usersMeRetrieve(),
});
