/**
 * This file is auto-generated by @hey-api/openapi-ts
 * Run `pnpm openapi-ts` to regenerate
 */

import { createClient } from '@hey-api/client-fetch';

export const client = createClient({
  baseUrl: '',
});
