/**
 * This file is auto-generated by @hey-api/openapi-ts
 * Run `pnpm openapi-ts` to regenerate
 */

import { client } from './client/client.gen';
import type { User } from './types.gen';

export const usersMeRetrieve = async (): Promise<User> => {
  const response = await client.get<User>({
    url: '/api/users/me/',
  });
  return response.data!;
};
