/**
 * This file is auto-generated by @hey-api/openapi-ts
 * Run `pnpm openapi-ts` to regenerate
 */

export interface User {
  id: number;
  email: string;
  name?: string;
}

export interface UsersMeRetrieveResponse {
  data: User;
}
